export const SSL_SECRET = '457SCZwkyRl4EdnVh/ps8bTiuac03brNA7y8EtaKrOo='
export const GOOGLE_CLIENT_ID = '415317828175-tlr8pb7pj01e74pkvrlj9h8os4qtbdq2.apps.googleusercontent.com'
export const GOOGLE_SECRET = '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'
export const KEYCLOAK_ISSUER = 'https://i13ventureskeycloak.azurewebsites.net/realms/Bob'
export const KEYCLOAK_SECRET = 'p2xBq0AHi0s9CEW3qGBQnBw6XRyRLETB'
export const KEYCLOAK_CLIENT_ID = 'bobUI'
export const KEYCLOAK_TOKEN_URL = 'https://i13ventureskeycloak.azurewebsites.net/realms/Bob/protocol/openid-connect/auth'
export const BOB_BACKEND = ''
// export const BOB_CARDS = 'http://localhost:4000'
export const BOB_CARDS = 'https://bob-cards-nodejs-mongodb.vercel.app'
export const FRONTEND_URL = 'http://localhost:3000/'

