"use client";
import React, { useEffect } from "react";
import PersonaCard from "./PersonaCard";
import CheckIcon from "@mui/icons-material/Check";
import ClearIcon from "@mui/icons-material/Clear";
import { Alert, IconButton } from "@mui/material";
import PersonaConfirmationModal from "../PersonaConfirmationModal";
import { appSlice, useDispatch } from "@/lib/redux";

const PersonaCanvas = () => {
    const dispatch = useDispatch();

    useEffect(() => {
        dispatch(appSlice.actions.togglePersonaConfirmationModal(true));
    }, []);

    const personaCards = [
        {
            roleName: "CEO",
            metaData: {
                age: "45",
                gender: "male",
            },
            cards: [
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Details",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec5",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Skills & Certs",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec6",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Languages",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec7",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Behavioural Char",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec8",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Professional Char",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec9",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Linkedin Intrests",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec2",
                },
            ],
        },
        {
            roleName: "CFO",
            metaData: {
                age: "25",
                gender: "Female",
            },
            cards: [
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Details",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec5",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Skills & Certs",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec6",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Languages",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec7",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Behavioural Char",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec8",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Professional Char",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec9",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Linkedin Intrests",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec2",
                },
            ],
        },
        {
            roleName: "Freelance",
            metaData: {
                age: "30",
                gender: "male",
            },
            cards: [
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Details",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec5",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Skills & Certs",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec6",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Languages",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec7",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Behavioural Char",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec8",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Professional Char",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec9",
                },
                {
                    cardCanvas: "Persona",
                    future: 1,
                    cardNumber: 0,
                    cardName: "Linkedin Intrests",
                    selected: false,
                    keyPoints: "",
                    locked: false,
                    loadingKeyPoints: false,
                    chat: [],
                    size: "full",
                    labelHeading: "",
                    label: [],
                    surety: 0,
                    userLock: false,
                    shared: [],
                    color: "#fff",
                    comments: [],
                    id: "655a8d0e03bce43fdecadec2",
                },
            ],
        },
    ];

    return (
        <>
            <div className="relative grid grid-cols-12 grid-rows-6 gap-4 select-none max-h-full w-full h-full">
                {personaCards?.map((data: any, index: any) => {
                    return <div key={index} className="row-span-6 col-span-4">
                        <PersonaCard card={data} />
                    </div>;
                })}
                {/* <div className="absolute w-[97.5%] top-[60px] left-2">
                    <div className="border-2 h-[270px] border-blue-500 rounded-md z-[1000]"></div>
                    <div className="flex justify-end items-center w-full mt-2">
                        <IconButton className="!mr-3 !bg-green-500 !text-white">
                            <CheckIcon />
                        </IconButton>
                        <IconButton className="!bg-red-500 !text-white">
                            <ClearIcon />
                        </IconButton>
                    </div>
                </div> */}
            </div>
            <PersonaConfirmationModal />
        </>
    );
};

export default PersonaCanvas;
