'use client';
import CanvasCard from '@/app/components/MicroFrameWorks/CanvasCard'
import { useTheme } from '@mui/material'
import React from 'react'

const page = () => {
  const theme: any = useTheme()
  const personaCards = [
    {
      roleName: "CEO",
      metaData: {
        age: "45",
        gender: "male",
      },
      cards: [
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Details",
          selected: true,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec5",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Skills & Certs",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec6",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Languages",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec7",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Behavioural Char",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec8",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Professional Char",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec9",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Linkedin Intrests",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec2",
        },
      ],
    },
    {
      roleName: "CFO",
      metaData: {
        age: "25",
        gender: "Female",
      },
      cards: [
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Details",
          selected: true,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec5",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Skills & Certs",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec6",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Languages",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec7",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Behavioural Char",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec8",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Professional Char",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec9",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Linkedin Intrests",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec2",
        },
      ],
    },
    {
      roleName: "Freelance",
      metaData: {
        age: "30",
        gender: "male",
      },
      cards: [
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Details",
          selected: true,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec5",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Skills & Certs",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec6",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Languages",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec7",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Behavioural Char",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec8",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Professional Char",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec9",
        },
        {
          cardCanvas: "Persona",
          future: 1,
          cardNumber: 0,
          cardName: "Linkedin Intrests",
          selected: false,
          keyPoints: "",
          locked: false,
          loadingKeyPoints: false,
          chat: [],
          size: "full",
          labelHeading: "",
          label: [],
          surety: 0,
          userLock: false,
          shared: [],
          color: "#fff",
          comments: [],
          id: "655a8d0e03bce43fdecadec2",
        },
      ],
    },
  ];
  return (
    <>
      <div className='grid grid-cols-12 auto-rows-auto gap-2 w-full h-full'>
        {
          personaCards[0]?.cards?.map((data: any) => {
            return (
              <div key={data?.id} className='col-span-4'>
                <CanvasCard
                  expand={true}
                  loading={false}
                  className={`${theme?.palette?.mode === "light"
                    ? "!bg-cyan-100"
                    : "!bg-cyan-900"
                    }`}
                  card={data}
                />
              </div>
            )
          })
        }
      </div>
    </>
  )
}

export default page